on:
  push:
    branches: master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      - name: Install packages
        run: |
          R -e 'install.packages(c("tidyverse", "reprex"))'

      - name: Build site
        run: Rscript 'make_episodes.R'

      - name: commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add docs
            git commit -m 'build gitbook'
            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
          fi
